; HEADER_BLOCK_START
; generated by OrcaSlicer 1.6.4-beta3 on 2023-08-17 at 19:04:34
; total layer number: 2
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START
; thumbnail begin 250x250 2232
; iVBORw0KGgoAAAANSUhEUgAAAPoAAAD6CAYAAACI7Fo9AAAGT0lEQVR4Ae3dz8oVZQAG8HfRomxRlO
; TiC4sISykV07RUcCW0k5YtIiJaBInQoijii4KC/vAFRYso7A66BC+hS+gSuoRT76mB09Hjd87MOzPv
; n98PHgiiDD+nGZ73YSYEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAACgLMcfPrsMUKnre7fCb1cX4adX/lr+NVCRIw88Gm6e+n15ka/mo9N3wtEHnw5A4Z5/5Nry
; Dr5+kXeJf+/c4zcCUKg3njnYeIGv550Tt5d3fqAQsWz7/NwfW1/kXeI/o6iDAnSFW990RZ27O2QoXp
; ixXBtykSvqIGNXjr2V7AJfv7vHfzcws1iijXGRryYezXmUhxnE0uzbC3+OfpF3ib+WYziY0I3j+5Nd
; 4OuP8vHXdneHEfU9NkudWNQ5hoMRDD02G+Pubi8PicTH5CkKtyF3d8dwMMDUhduQu7uiDnrYZaeeS+
; J/s6IOtpBL4dY39vJwiNwKt76xl4d72PRiiNKjqIP/HPZiiBru7vbyNK3Ewq1vvNiC5pRybJY6sahz
; DEcT5tqp5xJFHVWLf7BLPjZLHUUd1RnrxRClx16eauS8U88l8e7uUZ4itVq49Y29PMVp6dgsdezlyV
; 7pO/VcYi9PtmrZqecSRR1ZqXWnnkscwzG72nfqucRentko3KaPvTyTcWw2b+zlGZ3CLY/YyzOK1B8w
; lDRR1JGMnXrecQzHYHbq5cRenp0p3MqMvTxba/3FEDXEXp6N7NTrir08d3FsVmcUdSzl/gFDSRPHcA
; 1TuLUVRV2D7NTbjaKuAQo3iVHUVUzhJquxl6+MF0PI/aKoq0AsX7wYQg6LF1sUzLGZ7BovtiiIYzMZ
; Ei+2KICduqSIoi5TsUxxbCapo6jLiBdDyJixl5+ZnbpMGS+2mIHCTeaIvfyE7NRl7tjLj8hOXXKKvf
; wI7NQlxziGS8ROXUqIY7gBfMBQSoq9fA8KNyk19vJbcGwmNcRe/j4UblJTFHVrfMBQao6iLtipSxtp
; ei9vpy6tpam9vMJNWk4Te3kvhhD5N1Xu5e3URe5OVXt5x2Yim1NFUXd9bz/8eqWs33iROfLakwehWF
; ePHYQPX4z/1yrrN11kqvx4aRHeO7kIl5+4HYq2d+RauHVqEb4+X9YPQGTsfHFuEd58dhGOPXQtVCFe
; 7K8/dSd8fHoRfn61rB+GSOr8cnmxfNK9vnennot81ctH95d39+8vlvWDEUmV+Kj+7nOLcOax/VC17u
; 4eH1sUddJSPjlT8V18k3ixK+qkhXSFW7zIm7Ra1Lm7S42prnAbQlEntSUWbh+80PBdfJOuqPvuQlk/
; UJH1fPPPn+G3TzRQuPXVFXWfnfUoL2Wm6mOz1LqizjGclJLu2Myj+o4UdVJK9s8q3AbrijrHcJJbmj
; 82S81eXnLLV+fdxUexupf3KC9zpfqdei7s5WWuNLNTz0W8u79/cmEvL5Ml7tQ9qs/EXl7GjsItE47h
; ZKzYqWfIXl5SxU49c/byMjQHF+3Ui2AvL33T5IshSmcvL9vGTr1wijo5LAq3iijqZD2xcLt5yl28Ov
; by0sVOvXL28mKn3hB7+fZip94oe/l24sUQ2MtXHDt1/kdRV18cm3FPPgRZR1Z36i5yNlLUlRs7dXbi
; Q5DlxU6d3hR1+UfhRhL28vlG4UZyirp8YqfOqLzYYv50O3WFG6PqirpPz3iUnzp26kwu3t292GKa2K
; kzq66o+/Ild/exYqdONnwIMn0cm5Ele/l0cWxG1uzlh8UHDCmKvfzuUbhRJC+22D4+YEjx7OU3R+FG
; Vezl747CjWop6nzAkEa0vJf3Ygia0uKHIL0Ygma18CFIHzCEUHdRp3CDNTUVdbFwc2wGG9Swl/cBQ9
; hCyR+CtFOHHZW0l7dThwFK2Mt7MQQkkuNe3k4dRpBTUefYDEY094stfMAQJjTHXt5OHWYw5V7eTh1m
; 1hV1P1xKf4HbqUNGxtjLK9wgUymKOh8whAJ0RV2fYzgfMISC9NnL26lDobbZy9upQwW6ou5ee3k7da
; jM6l7eTh0q1t3d3cWhcvFid5EDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAEBx/gY0o5dKFTbDVgAAAABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.44mm
; perimeters extrusion width = 0.42mm
; infill extrusion width = 0.50mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.56mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=110,110 POLYGON=[[87.5,87.5],[132.5,87.5],[132.5,132.5],[87.5,132.5],[87.5,87.5]]
M73 P0 R2
;TYPE:Custom
M190 S0 ; Remove this if autoemit_temperature_commands is off in Prusa Slicer 2.6 and later
M109 S0 ; Remove this if autoemit_temperature_commands is off in Prusa Slicer 2.6 and later
_PRINT_START_PHASE_INIT EXTRUDER=230 BED=60 MESH_MIN=87.5,87.5 MESH_MAX=132.5,132.5 LAYERS=2 NOZZLE_SIZE=0.4
; Insert custom gcode here.
_PRINT_START_PHASE_PREHEAT
; Insert custom gcode here.
_PRINT_START_PHASE_PROBING
; Insert custom gcode here.
_PRINT_START_PHASE_EXTRUDER
; Insert custom gcode here.
_PRINT_START_PHASE_PURGE

; This is the place to put slicer purge lines if you haven't set a non-zero
; variable_start_purge_length to have START_PRINT automatically calculate and 
; perform the purge (e.g. if using a Mosaic Palette, which requires the slicer
; to generate the purge).
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
;LAYER_CHANGE
;Z:0.36
;HEIGHT:0.36
;BEFORE_LAYER_CHANGE
;0.36
BEFORE_LAYER_CHANGE HEIGHT=0.36 LAYER=0
G1 E-.4 F1800
;AFTER_LAYER_CHANGE
;0.36
AFTER_LAYER_CHANGE
SET_VELOCITY_LIMIT ACCEL=3000 ACCEL_TO_DECEL=1500
; printing object Cube id:0 copy 0
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 Z.4 F9000
G1 X88.745 Y88.745
G1 Z.4
G1 Z.36
G1 E.4 F1200
;TYPE:Inner wall
;WIDTH:0.56
G1 F3000
G1 X131.255 Y88.745 E3.16045
M73 P1 R2
G1 X131.255 Y131.255 E3.16045
M73 P2 R2
G1 X88.745 Y131.255 E3.16045
G1 X88.745 Y88.785 E3.15748
M73 P3 R2
G1 X88.263 Y88.263 F9000
G1 F3000
G1 X131.737 Y88.263 E3.23224
M73 P4 R2
G1 X131.737 Y131.737 E3.23224
G1 X88.263 Y131.737 E3.23224
M73 P5 R2
G1 X88.263 Y88.303 E3.22926
M73 P6 R2
G1 X87.78 Y87.78 F9000
;TYPE:Outer wall
G1 F3000
G1 X132.22 Y87.78 E3.30402
G1 X132.22 Y132.22 E3.30402
M73 P7 R2
G1 X87.78 Y132.22 E3.30402
M73 P8 R2
G1 X87.78 Y87.82 E3.30104
G1 E-.4 F1800
G1 Z.76 F9000
G1 X130.127 Y88.89 Z.76
M73 P9 R2
G1 Z.36
G1 E.4 F1200
;TYPE:Internal solid infill
;WIDTH:0.563236
G1 F3000
G1 X130.892 Y89.656 E.08102
G1 X130.892 Y90.343 E.05144
G1 X129.657 Y89.108 E.13078
G1 X128.97 Y89.108 E.05144
G1 X130.892 Y91.03 E.20353
G1 X130.892 Y91.718 E.05144
G1 X128.282 Y89.108 E.27627
G1 X127.595 Y89.108 E.05144
G1 X130.892 Y92.405 E.34902
G1 X130.892 Y93.092 E.05144
G1 X126.908 Y89.108 E.42177
G1 X126.221 Y89.108 E.05144
M73 P9 R1
G1 X130.892 Y93.779 E.49451
G1 X130.892 Y94.467 E.05144
G1 X125.533 Y89.108 E.56726
M73 P10 R1
G1 X124.846 Y89.108 E.05144
G1 X130.892 Y95.154 E.64001
G1 X130.892 Y95.841 E.05144
G1 X124.159 Y89.108 E.71276
G1 X123.471 Y89.108 E.05144
G1 X130.892 Y96.529 E.7855
G1 X130.892 Y97.216 E.05144
G1 X122.784 Y89.108 E.85825
G1 X122.097 Y89.108 E.05144
G1 X130.892 Y97.903 E.931
M73 P11 R1
G1 X130.892 Y98.59 E.05144
G1 X121.41 Y89.108 E1.00375
G1 X120.722 Y89.108 E.05144
G1 X130.892 Y99.278 E1.07649
G1 X130.892 Y99.965 E.05144
G1 X120.035 Y89.108 E1.14924
G1 X119.348 Y89.108 E.05144
G1 X130.892 Y100.652 E1.22199
M73 P12 R1
G1 X130.892 Y101.34 E.05144
G1 X118.66 Y89.108 E1.29473
G1 X117.973 Y89.108 E.05144
G1 X130.892 Y102.027 E1.36748
G1 X130.892 Y102.714 E.05144
G1 X117.286 Y89.108 E1.44023
G1 X116.599 Y89.108 E.05144
M73 P13 R1
G1 X130.892 Y103.401 E1.51298
G1 X130.892 Y104.089 E.05144
G1 X115.911 Y89.108 E1.58572
G1 X115.224 Y89.108 E.05144
G1 X130.892 Y104.776 E1.65847
M73 P14 R1
G1 X130.892 Y105.463 E.05144
G1 X114.537 Y89.108 E1.73122
G1 X113.85 Y89.108 E.05144
G1 X130.892 Y106.15 E1.80397
G1 X130.892 Y106.838 E.05144
G1 X113.162 Y89.108 E1.87671
M73 P15 R1
G1 X112.475 Y89.108 E.05144
G1 X130.892 Y107.525 E1.94946
G1 X130.892 Y108.212 E.05144
G1 X111.788 Y89.108 E2.02221
M73 P16 R1
G1 X111.1 Y89.108 E.05144
G1 X130.892 Y108.9 E2.09496
G1 X130.892 Y109.587 E.05144
G1 X110.413 Y89.108 E2.1677
M73 P17 R1
G1 X109.726 Y89.108 E.05144
G1 X130.892 Y110.274 E2.24045
G1 X130.892 Y110.961 E.05144
G1 X109.039 Y89.108 E2.3132
M73 P18 R1
G1 X108.351 Y89.108 E.05144
G1 X130.892 Y111.649 E2.38594
G1 X130.892 Y112.336 E.05144
G1 X107.664 Y89.108 E2.45869
M73 P19 R1
G1 X106.977 Y89.108 E.05144
G1 X130.892 Y113.023 E2.53144
G1 X130.892 Y113.711 E.05144
G1 X106.289 Y89.108 E2.60419
M73 P20 R1
G1 X105.602 Y89.108 E.05144
G1 X130.892 Y114.398 E2.67693
G1 X130.892 Y115.085 E.05144
G1 X104.915 Y89.108 E2.74968
M73 P21 R1
G1 X104.228 Y89.108 E.05144
G1 X130.892 Y115.772 E2.82243
G1 X130.892 Y116.46 E.05144
G1 X103.54 Y89.108 E2.89518
M73 P22 R1
G1 X102.853 Y89.108 E.05144
G1 X130.892 Y117.147 E2.96792
M73 P23 R1
G1 X130.892 Y117.834 E.05144
G1 X102.166 Y89.108 E3.04067
G1 X101.479 Y89.108 E.05144
G1 X130.892 Y118.521 E3.11342
M73 P24 R1
G1 X130.892 Y119.209 E.05144
G1 X100.791 Y89.108 E3.18616
M73 P25 R1
G1 X100.104 Y89.108 E.05144
G1 X130.892 Y119.896 E3.25891
G1 X130.892 Y120.583 E.05144
G1 X99.417 Y89.108 E3.33166
M73 P26 R1
G1 X98.729 Y89.108 E.05144
G1 X130.892 Y121.271 E3.40441
M73 P27 R1
G1 X130.892 Y121.958 E.05144
G1 X98.042 Y89.108 E3.47715
M73 P28 R1
G1 X97.355 Y89.108 E.05144
G1 X130.892 Y122.645 E3.5499
G1 X130.892 Y123.332 E.05144
G1 X96.668 Y89.108 E3.62265
M73 P29 R1
G1 X95.98 Y89.108 E.05144
G1 X130.892 Y124.02 E3.6954
M73 P30 R1
G1 X130.892 Y124.707 E.05144
G1 X95.293 Y89.108 E3.76814
M73 P31 R1
G1 X94.606 Y89.108 E.05144
G1 X130.892 Y125.394 E3.84089
G1 X130.892 Y126.082 E.05144
G1 X93.918 Y89.108 E3.91364
M73 P32 R1
G1 X93.231 Y89.108 E.05144
G1 X130.892 Y126.769 E3.98639
M73 P33 R1
G1 X130.892 Y127.456 E.05144
G1 X92.544 Y89.108 E4.05913
M73 P34 R1
G1 X91.857 Y89.108 E.05144
G1 X130.892 Y128.143 E4.13188
M73 P35 R1
G1 X130.892 Y128.831 E.05144
G1 X91.169 Y89.108 E4.20463
M73 P36 R1
G1 X90.482 Y89.108 E.05144
G1 X130.892 Y129.518 E4.27737
M73 P37 R1
G1 X130.892 Y130.205 E.05144
G1 X89.795 Y89.108 E4.35012
G1 X89.108 Y89.108 E.05144
G1 X130.892 Y130.892 E4.42287
M73 P38 R1
G1 X130.205 Y130.892 E.05144
G1 X89.108 Y89.795 E4.35012
M73 P39 R1
G1 X89.108 Y90.482 E.05144
G1 X129.518 Y130.892 E4.27738
M73 P40 R1
G1 X128.831 Y130.892 E.05144
G1 X89.108 Y91.169 E4.20463
M73 P41 R1
G1 X89.108 Y91.857 E.05144
G1 X128.143 Y130.892 E4.13188
M73 P42 R1
G1 X127.456 Y130.892 E.05144
G1 X89.108 Y92.544 E4.05913
M73 P43 R1
G1 X89.108 Y93.231 E.05144
G1 X126.769 Y130.892 E3.98639
M73 P44 R1
G1 X126.082 Y130.892 E.05144
G1 X89.108 Y93.918 E3.91364
G1 X89.108 Y94.606 E.05144
G1 X125.394 Y130.892 E3.84089
M73 P45 R1
G1 X124.707 Y130.892 E.05144
G1 X89.108 Y95.293 E3.76815
M73 P46 R1
G1 X89.108 Y95.98 E.05144
G1 X124.02 Y130.892 E3.6954
M73 P47 R1
G1 X123.332 Y130.892 E.05144
G1 X89.108 Y96.668 E3.62265
M73 P48 R1
G1 X89.108 Y97.355 E.05144
G1 X122.645 Y130.892 E3.5499
G1 X121.958 Y130.892 E.05144
G1 X89.108 Y98.042 E3.47716
M73 P49 R1
G1 X89.108 Y98.729 E.05144
G1 X121.271 Y130.892 E3.40441
M73 P50 R1
G1 X120.583 Y130.892 E.05144
G1 X89.108 Y99.417 E3.33166
M73 P51 R1
G1 X89.108 Y100.104 E.05144
G1 X119.896 Y130.892 E3.25891
G1 X119.209 Y130.892 E.05144
G1 X89.108 Y100.791 E3.18617
M73 P52 R1
G1 X89.108 Y101.479 E.05144
G1 X118.521 Y130.892 E3.11342
M73 P53 R1
G1 X117.834 Y130.892 E.05144
G1 X89.108 Y102.166 E3.04067
G1 X89.108 Y102.853 E.05144
G1 X117.147 Y130.892 E2.96792
M73 P54 R1
G1 X116.46 Y130.892 E.05144
G1 X89.108 Y103.54 E2.89518
G1 X89.108 Y104.228 E.05144
G1 X115.772 Y130.892 E2.82243
M73 P55 R0
G1 X115.085 Y130.892 E.05144
G1 X89.108 Y104.915 E2.74968
M73 P56 R0
G1 X89.108 Y105.602 E.05144
G1 X114.398 Y130.892 E2.67694
G1 X113.711 Y130.892 E.05144
G1 X89.108 Y106.289 E2.60419
M73 P57 R0
G1 X89.108 Y106.977 E.05144
G1 X113.023 Y130.892 E2.53144
G1 X112.336 Y130.892 E.05144
G1 X89.108 Y107.664 E2.45869
M73 P58 R0
G1 X89.108 Y108.351 E.05144
G1 X111.649 Y130.892 E2.38595
G1 X110.961 Y130.892 E.05144
G1 X89.108 Y109.039 E2.3132
M73 P59 R0
G1 X89.108 Y109.726 E.05144
G1 X110.274 Y130.892 E2.24045
G1 X109.587 Y130.892 E.05144
G1 X89.108 Y110.413 E2.1677
M73 P60 R0
G1 X89.108 Y111.1 E.05144
G1 X108.9 Y130.892 E2.09496
G1 X108.212 Y130.892 E.05144
G1 X89.108 Y111.788 E2.02221
M73 P61 R0
G1 X89.108 Y112.475 E.05144
G1 X107.525 Y130.892 E1.94946
G1 X106.838 Y130.892 E.05144
G1 X89.108 Y113.162 E1.87672
M73 P62 R0
G1 X89.108 Y113.85 E.05144
G1 X106.15 Y130.892 E1.80397
G1 X105.463 Y130.892 E.05144
G1 X89.108 Y114.537 E1.73122
G1 X89.108 Y115.224 E.05144
G1 X104.776 Y130.892 E1.65847
M73 P63 R0
G1 X104.089 Y130.892 E.05144
G1 X89.108 Y115.911 E1.58573
G1 X89.108 Y116.599 E.05144
G1 X103.401 Y130.892 E1.51298
G1 X102.714 Y130.892 E.05144
G1 X89.108 Y117.286 E1.44023
M73 P64 R0
G1 X89.108 Y117.973 E.05144
G1 X102.027 Y130.892 E1.36748
G1 X101.34 Y130.892 E.05144
G1 X89.108 Y118.66 E1.29474
G1 X89.108 Y119.348 E.05144
G1 X100.652 Y130.892 E1.22199
M73 P65 R0
G1 X99.965 Y130.892 E.05144
G1 X89.108 Y120.035 E1.14924
G1 X89.108 Y120.722 E.05144
G1 X99.278 Y130.892 E1.0765
G1 X98.59 Y130.892 E.05144
G1 X89.108 Y121.41 E1.00375
G1 X89.108 Y122.097 E.05144
G1 X97.903 Y130.892 E.931
M73 P66 R0
G1 X97.216 Y130.892 E.05144
G1 X89.108 Y122.784 E.85825
G1 X89.108 Y123.471 E.05144
G1 X96.529 Y130.892 E.78551
G1 X95.841 Y130.892 E.05144
G1 X89.108 Y124.159 E.71276
G1 X89.108 Y124.846 E.05144
G1 X95.154 Y130.892 E.64001
G1 X94.467 Y130.892 E.05144
G1 X89.108 Y125.533 E.56726
G1 X89.108 Y126.221 E.05144
G1 X93.779 Y130.892 E.49452
M73 P67 R0
G1 X93.092 Y130.892 E.05144
G1 X89.108 Y126.908 E.42177
G1 X89.108 Y127.595 E.05144
G1 X92.405 Y130.892 E.34902
G1 X91.718 Y130.892 E.05144
G1 X89.108 Y128.282 E.27627
G1 X89.108 Y128.97 E.05144
G1 X91.03 Y130.892 E.20353
G1 X90.343 Y130.892 E.05144
G1 X89.108 Y129.657 E.13078
G1 X89.108 Y130.344 E.05144
G1 X89.873 Y131.11 E.08103
; stop printing object Cube id:0 copy 0
M106 S255

;LAYER_CHANGE
;Z:0.56
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.56
BEFORE_LAYER_CHANGE HEIGHT=0.56 LAYER=1
G1 E-.28 F1800
;WIPE_START
G1 F3000
G1 X89.166 Y130.403 E-.114
;WIPE_END
G1 E-.006 F1800
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
;AFTER_LAYER_CHANGE
;0.56
AFTER_LAYER_CHANGE
M140 S60 ; set bed temperature
; printing object Cube id:0 copy 0
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 Z.76 F18000
G1 X88.484 Y131.516 Z.76
G1 Z.56
G1 E.4 F1200
;TYPE:Inner wall
;WIDTH:0.42
G1 F14320.583
G1 X88.484 Y88.484 E1.38836
M73 P68 R0
G1 X131.516 Y88.484 E1.38836
G1 X131.516 Y131.516 E1.38836
G1 X88.524 Y131.516 E1.38707
G1 X88.107 Y131.893 F18000
G1 F14320.583
G1 X88.107 Y88.107 E1.41269
M73 P69 R0
G1 X131.893 Y88.107 E1.41269
G1 X131.893 Y131.893 E1.41269
G1 X88.147 Y131.893 E1.4114
G1 X87.72 Y132.28 F18000
;TYPE:Outer wall
;WIDTH:0.44
G1 F12000
G1 X87.72 Y87.72 E1.51392
M73 P70 R0
G1 X102.200 Y87.72 E0.49196
M106 S227
G1 X132.28 Y87.72 E1.02196
G1 X132.28 Y132.28 E1.51392
G1 X87.76 Y132.28 E1.51256
G1 E-.4 F1800
M73 P71 R0
G1 Z.96 F18000
G1 X130.639 Y131.405 Z.96
G1 Z.56
G1 E.4 F1200
;TYPE:Top surface
;WIDTH:0.421647
G1 F12000
G1 X131.236 Y130.809 E.02732
G1 X131.236 Y130.274 E.01736
G1 X130.274 Y131.236 E.04409
G1 X129.738 Y131.236 E.01736
G1 X131.236 Y129.738 E.06863
G1 X131.236 Y129.202 E.01736
G1 X129.202 Y131.236 E.09318
G1 X128.667 Y131.236 E.01736
G1 X131.236 Y128.667 E.11772
G1 X131.236 Y128.131 E.01736
G1 X128.131 Y131.236 E.14227
G1 X127.596 Y131.236 E.01736
G1 X131.236 Y127.596 E.16681
G1 X131.236 Y127.06 E.01736
G1 X127.06 Y131.236 E.19135
G1 X126.524 Y131.236 E.01736
G1 X131.236 Y126.524 E.2159
M73 P72 R0
G1 X131.236 Y125.989 E.01736
G1 X125.989 Y131.236 E.24044
G1 X125.453 Y131.236 E.01736
G1 X131.236 Y125.453 E.26499
G1 X131.236 Y124.918 E.01736
G1 X124.918 Y131.236 E.28953
G1 X124.382 Y131.236 E.01736
G1 X131.236 Y124.382 E.31408
G1 X131.236 Y123.846 E.01736
G1 X123.846 Y131.236 E.33862
G1 X123.311 Y131.236 E.01736
G1 X131.236 Y123.311 E.36317
G1 X131.236 Y122.775 E.01736
G1 X122.775 Y131.236 E.38771
G1 X122.24 Y131.236 E.01736
G1 X131.236 Y122.24 E.41226
G1 X131.236 Y121.704 E.01736
G1 X121.704 Y131.236 E.4368
G1 X121.168 Y131.236 E.01736
M73 P73 R0
G1 X131.236 Y121.168 E.46135
G1 X131.236 Y120.633 E.01736
G1 X120.633 Y131.236 E.48589
G1 X120.097 Y131.236 E.01736
G1 X131.236 Y120.097 E.51044
G1 X131.236 Y119.562 E.01736
G1 X119.562 Y131.236 E.53498
G1 X119.026 Y131.236 E.01736
G1 X131.236 Y119.026 E.55953
G1 X131.236 Y118.49 E.01736
G1 X118.49 Y131.236 E.58407
G1 X117.955 Y131.236 E.01736
G1 X131.236 Y117.955 E.60862
G1 X131.236 Y117.419 E.01736
G1 X117.419 Y131.236 E.63316
M73 P74 R0
G1 X116.884 Y131.236 E.01736
G1 X131.236 Y116.884 E.65771
G1 X131.236 Y116.348 E.01736
G1 X116.348 Y131.236 E.68225
G1 X115.812 Y131.236 E.01736
G1 X131.236 Y115.812 E.7068
G1 X131.236 Y115.277 E.01736
G1 X115.277 Y131.236 E.73134
G1 X114.741 Y131.236 E.01736
G1 X131.236 Y114.741 E.75589
G1 X131.236 Y114.206 E.01736
G1 X114.206 Y131.236 E.78043
G1 X113.67 Y131.236 E.01736
G1 X131.236 Y113.67 E.80498
M73 P75 R0
G1 X131.236 Y113.134 E.01736
G1 X113.134 Y131.236 E.82952
G1 X112.599 Y131.236 E.01736
G1 X131.236 Y112.599 E.85407
G1 X131.236 Y112.063 E.01736
G1 X112.063 Y131.236 E.87861
G1 X111.528 Y131.236 E.01736
G1 X131.236 Y111.528 E.90316
G1 X131.236 Y110.992 E.01736
G1 X110.992 Y131.236 E.9277
G1 X110.456 Y131.236 E.01736
G1 X131.236 Y110.456 E.95225
M73 P76 R0
G1 X131.236 Y109.921 E.01736
G1 X109.921 Y131.236 E.97679
G1 X109.385 Y131.236 E.01736
G1 X131.236 Y109.385 E1.00134
G1 X131.236 Y108.85 E.01736
G1 X108.85 Y131.236 E1.02588
G1 X108.314 Y131.236 E.01736
G1 X131.236 Y108.314 E1.05043
G1 X131.236 Y107.778 E.01736
G1 X107.778 Y131.236 E1.07497
M73 P77 R0
G1 X107.243 Y131.236 E.01736
G1 X131.236 Y107.243 E1.09952
G1 X131.236 Y106.707 E.01736
G1 X106.707 Y131.236 E1.12406
G1 X106.172 Y131.236 E.01736
G1 X131.236 Y106.172 E1.14861
G1 X131.236 Y105.636 E.01736
G1 X105.636 Y131.236 E1.17315
G1 X105.1 Y131.236 E.01736
G1 X131.236 Y105.1 E1.1977
M73 P78 R0
G1 X131.236 Y104.565 E.01736
G1 X104.565 Y131.236 E1.22224
G1 X104.029 Y131.236 E.01736
G1 X131.236 Y104.029 E1.24679
G1 X131.236 Y103.494 E.01736
G1 X103.494 Y131.236 E1.27133
G1 X102.958 Y131.236 E.01736
G1 X131.236 Y102.958 E1.29588
G1 X131.236 Y102.422 E.01736
G1 X102.422 Y131.236 E1.32042
M73 P79 R0
G1 X101.887 Y131.236 E.01736
G1 X131.236 Y101.887 E1.34497
G1 X131.236 Y101.351 E.01736
G1 X101.351 Y131.236 E1.36951
G1 X100.816 Y131.236 E.01736
G1 X131.236 Y100.816 E1.39406
G1 X131.236 Y100.28 E.01736
G1 X100.28 Y131.236 E1.4186
M73 P80 R0
G1 X99.744 Y131.236 E.01736
G1 X131.236 Y99.744 E1.44315
G1 X131.236 Y99.209 E.01736
G1 X99.209 Y131.236 E1.46769
G1 X98.673 Y131.236 E.01736
G1 X131.236 Y98.673 E1.49224
G1 X131.236 Y98.138 E.01736
G1 X98.137 Y131.236 E1.51678
M73 P81 R0
G1 X97.602 Y131.236 E.01736
G1 X131.236 Y97.602 E1.54133
G1 X131.236 Y97.066 E.01736
G1 X97.066 Y131.236 E1.56587
G1 X96.531 Y131.236 E.01736
G1 X131.236 Y96.531 E1.59042
G1 X131.236 Y95.995 E.01736
G1 X95.995 Y131.236 E1.61496
M73 P82 R0
G1 X95.459 Y131.236 E.01736
G1 X131.236 Y95.46 E1.63951
G1 X131.236 Y94.924 E.01736
G1 X94.924 Y131.236 E1.66405
G1 X94.388 Y131.236 E.01736
G1 X131.236 Y94.388 E1.6886
G1 X131.236 Y93.853 E.01736
G1 X93.853 Y131.236 E1.71314
M73 P83 R0
G1 X93.317 Y131.236 E.01736
G1 X131.236 Y93.317 E1.73769
G1 X131.236 Y92.781 E.01736
G1 X92.781 Y131.236 E1.76223
G1 X92.246 Y131.236 E.01736
G1 X131.236 Y92.246 E1.78678
G1 X131.236 Y91.71 E.01736
G1 X91.71 Y131.236 E1.81132
M73 P84 R0
G1 X91.175 Y131.236 E.01736
G1 X131.236 Y91.175 E1.83587
G1 X131.236 Y90.639 E.01736
G1 X90.639 Y131.236 E1.86041
G1 X90.103 Y131.236 E.01736
G1 X131.236 Y90.103 E1.88496
M73 P85 R0
G1 X131.236 Y89.568 E.01736
G1 X89.568 Y131.236 E1.9095
G1 X89.032 Y131.236 E.01736
G1 X131.236 Y89.032 E1.93405
G1 X131.236 Y88.764 E.00868
G1 X130.968 Y88.764 E.00868
G1 X88.764 Y130.968 E1.93405
G1 X88.764 Y130.432 E.01736
G1 X130.432 Y88.764 E1.9095
M73 P86 R0
G1 X129.897 Y88.764 E.01736
G1 X88.764 Y129.897 E1.88496
G1 X88.764 Y129.361 E.01736
G1 X129.361 Y88.764 E1.86041
G1 X128.825 Y88.764 E.01736
G1 X88.764 Y128.825 E1.83587
M73 P87 R0
G1 X88.764 Y128.29 E.01736
G1 X128.29 Y88.764 E1.81132
G1 X127.754 Y88.764 E.01736
G1 X88.764 Y127.754 E1.78678
G1 X88.764 Y127.219 E.01736
G1 X127.219 Y88.764 E1.76223
G1 X126.683 Y88.764 E.01736
G1 X88.764 Y126.683 E1.73769
M73 P88 R0
G1 X88.764 Y126.147 E.01736
G1 X126.147 Y88.764 E1.71314
G1 X125.612 Y88.764 E.01736
G1 X88.764 Y125.612 E1.6886
G1 X88.764 Y125.076 E.01736
G1 X125.076 Y88.764 E1.66405
G1 X124.541 Y88.764 E.01736
M73 P89 R0
G1 X88.764 Y124.541 E1.63951
G1 X88.764 Y124.005 E.01736
G1 X124.005 Y88.764 E1.61496
G1 X123.469 Y88.764 E.01736
G1 X88.764 Y123.469 E1.59042
G1 X88.764 Y122.934 E.01736
G1 X122.934 Y88.764 E1.56587
M73 P90 R0
G1 X122.398 Y88.764 E.01736
G1 X88.764 Y122.398 E1.54133
G1 X88.764 Y121.863 E.01736
G1 X121.863 Y88.764 E1.51678
G1 X121.327 Y88.764 E.01736
G1 X88.764 Y121.327 E1.49224
G1 X88.764 Y120.791 E.01736
G1 X120.791 Y88.764 E1.46769
G1 X120.256 Y88.764 E.01736
M73 P91 R0
G1 X88.764 Y120.256 E1.44315
G1 X88.764 Y119.72 E.01736
G1 X119.72 Y88.764 E1.4186
G1 X119.185 Y88.764 E.01736
G1 X88.764 Y119.185 E1.39406
G1 X88.764 Y118.649 E.01736
G1 X118.649 Y88.764 E1.36951
G1 X118.113 Y88.764 E.01736
G1 X88.764 Y118.113 E1.34497
M73 P92 R0
G1 X88.764 Y117.578 E.01736
G1 X117.578 Y88.764 E1.32043
G1 X117.042 Y88.764 E.01736
G1 X88.764 Y117.042 E1.29588
G1 X88.764 Y116.507 E.01736
G1 X116.507 Y88.764 E1.27134
G1 X115.971 Y88.764 E.01736
G1 X88.764 Y115.971 E1.24679
M73 P93 R0
G1 X88.764 Y115.435 E.01736
G1 X115.435 Y88.764 E1.22225
G1 X114.9 Y88.764 E.01736
G1 X88.764 Y114.9 E1.1977
G1 X88.764 Y114.364 E.01736
G1 X114.364 Y88.764 E1.17316
G1 X113.829 Y88.764 E.01736
G1 X88.764 Y113.829 E1.14861
G1 X88.764 Y113.293 E.01736
G1 X113.293 Y88.764 E1.12407
M73 P94 R0
G1 X112.757 Y88.764 E.01736
G1 X88.764 Y112.757 E1.09952
G1 X88.764 Y112.222 E.01736
G1 X112.222 Y88.764 E1.07498
G1 X111.686 Y88.764 E.01736
G1 X88.764 Y111.686 E1.05043
G1 X88.764 Y111.151 E.01736
G1 X111.151 Y88.764 E1.02589
G1 X110.615 Y88.764 E.01736
G1 X88.764 Y110.615 E1.00134
M73 P95 R0
G1 X88.764 Y110.079 E.01736
G1 X110.079 Y88.764 E.9768
G1 X109.544 Y88.764 E.01736
G1 X88.764 Y109.544 E.95225
G1 X88.764 Y109.008 E.01736
G1 X109.008 Y88.764 E.92771
G1 X108.473 Y88.764 E.01736
G1 X88.764 Y108.473 E.90316
G1 X88.764 Y107.937 E.01736
G1 X107.937 Y88.764 E.87862
G1 X107.401 Y88.764 E.01736
G1 X88.764 Y107.401 E.85407
M73 P96 R0
G1 X88.764 Y106.866 E.01736
G1 X106.866 Y88.764 E.82953
G1 X106.33 Y88.764 E.01736
G1 X88.764 Y106.33 E.80498
G1 X88.764 Y105.795 E.01736
G1 X105.795 Y88.764 E.78044
G1 X105.259 Y88.764 E.01736
G1 X88.764 Y105.259 E.75589
G1 X88.764 Y104.723 E.01736
G1 X104.723 Y88.764 E.73135
G1 X104.188 Y88.764 E.01736
G1 X88.764 Y104.188 E.7068
M73 P97 R0
G1 X88.764 Y103.652 E.01736
G1 X103.652 Y88.764 E.68226
G1 X103.117 Y88.764 E.01736
G1 X88.764 Y103.117 E.65771
G1 X88.764 Y102.581 E.01736
G1 X102.581 Y88.764 E.63317
G1 X102.045 Y88.764 E.01736
G1 X88.764 Y102.045 E.60862
G1 X88.764 Y101.51 E.01736
G1 X101.51 Y88.764 E.58408
G1 X100.974 Y88.764 E.01736
G1 X88.764 Y100.974 E.55953
G1 X88.764 Y100.439 E.01736
G1 X100.439 Y88.764 E.53499
G1 X99.903 Y88.764 E.01736
M73 P98 R0
G1 X88.764 Y99.903 E.51044
G1 X88.764 Y99.367 E.01736
G1 X99.367 Y88.764 E.4859
G1 X98.832 Y88.764 E.01736
G1 X88.764 Y98.832 E.46135
G1 X88.764 Y98.296 E.01736
G1 X98.296 Y88.764 E.43681
G1 X97.761 Y88.764 E.01736
G1 X88.764 Y97.761 E.41226
G1 X88.764 Y97.225 E.01736
G1 X97.225 Y88.764 E.38772
G1 X96.689 Y88.764 E.01736
G1 X88.764 Y96.689 E.36317
G1 X88.764 Y96.154 E.01736
G1 X96.154 Y88.764 E.33863
G1 X95.618 Y88.764 E.01736
G1 X88.764 Y95.618 E.31408
M73 P99 R0
G1 X88.764 Y95.083 E.01736
G1 X95.083 Y88.764 E.28954
G1 X94.547 Y88.764 E.01736
G1 X88.764 Y94.547 E.26499
G1 X88.764 Y94.011 E.01736
G1 X94.011 Y88.764 E.24045
G1 X93.476 Y88.764 E.01736
G1 X88.764 Y93.476 E.2159
G1 X88.764 Y92.94 E.01736
G1 X92.94 Y88.764 E.19136
G1 X92.405 Y88.764 E.01736
G1 X88.764 Y92.405 E.16681
G1 X88.764 Y91.869 E.01736
G1 X91.869 Y88.764 E.14227
G1 X91.333 Y88.764 E.01736
G1 X88.764 Y91.333 E.11772
G1 X88.764 Y90.798 E.01736
G1 X90.798 Y88.764 E.09318
G1 X90.262 Y88.764 E.01736
G1 X88.764 Y90.262 E.06863
G1 X88.764 Y89.727 E.01736
G1 X89.727 Y88.764 E.04409
G1 X89.191 Y88.764 E.01736
G1 X88.595 Y89.361 E.02732
; stop printing object Cube id:0 copy 0
G1 E-.28 F1800
;WIPE_START
G1 F12000
G1 X89.191 Y88.764 E-.09611
G1 X89.348 Y88.764 E-.01789
;WIPE_END
G1 E-.006 F1800
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
M106 S0
;TYPE:Custom
; filament end gcode 
PRINT_END
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 487.84
; filament used [cm3] = 1.17
; filament used [g] = 1.46
; filament cost = 0.03; total filament used [g] = 1.46
; total filament cost = 0.03
; total layers count = 2
; estimated printing time (normal mode) = 2m 12s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; additional_cooling_fan_speed = 70
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_temperature_difference = 10
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nBEFORE_LAYER_CHANGE HEIGHT=[layer_z] LAYER=[layer_num]
; bottom_shell_layers = 4
; bottom_shell_thickness = 1
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 0
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; curr_bed_type = High Temp Plate
; default_acceleration = 10000
; default_filament_colour = ""
; default_filament_profile = "My Generic ABS"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @MyKlipper
; deretraction_speed = 20
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = bottom_shell_layers;bottom_shell_thickness;default_acceleration;filter_out_gap_fill;gap_infill_speed;infill_combination;infill_jerk;initial_layer_acceleration;initial_layer_infill_speed;initial_layer_jerk;initial_layer_line_width;initial_layer_print_height;initial_layer_travel_speed;inner_wall_acceleration;inner_wall_jerk;inner_wall_line_width;inner_wall_speed;internal_solid_infill_line_width;line_width;max_travel_detour_distance;minimum_sparse_infill_area;outer_wall_acceleration;outer_wall_jerk;outer_wall_line_width;outer_wall_speed;reduce_crossing_wall;seam_position;slow_down_layers;small_perimeter_threshold;sparse_infill_density;sparse_infill_line_width;sparse_infill_pattern;sparse_infill_speed;top_shell_layers;top_shell_thickness;top_surface_acceleration;top_surface_jerk;top_surface_line_width;top_surface_speed;travel_acceleration;travel_jerk;travel_speed;wall_generator;fan_cooling_layer_time;fan_min_speed;filament_flow_ratio;filament_max_volumetric_speed;nozzle_temperature;nozzle_temperature_initial_layer;nozzle_temperature_range_high;overhang_fan_threshold;slow_down_layer_time;slow_down_min_speed;before_layer_change_gcode;deretraction_speed;fan_kickstart;fan_speedup_time;layer_change_gcode;machine_max_acceleration_e;machine_max_acceleration_extruding;machine_max_acceleration_retracting;machine_max_acceleration_x;machine_max_acceleration_y;machine_max_acceleration_z;machine_max_jerk_x;machine_max_jerk_y;machine_max_jerk_z;machine_max_speed_x;machine_max_speed_y;machine_start_gcode;print_host;printable_area;retraction_length;thumbnails
; draft_shield = disabled
; elefant_foot_compensation = 0
; enable_arc_fitting = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = 1
; exclude_object = 1
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 60
; fan_kickstart = 2
; fan_max_speed = 100
; fan_min_speed = 40
; fan_speedup_overhangs = 1
; fan_speedup_time = 1
; filament_colour = #00AE42
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 1.029
; filament_ids = GFL99
; filament_is_support = 0
; filament_max_volumetric_speed = 18
; filament_minimal_purge_on_wipe_tower = 15
; filament_settings_id = "Mercury1 - PLA"
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_type = PLA
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 5
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; host_type = octoprint
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 1
; infill_direction = 45
; infill_jerk = 2
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @MyKlipper";"My Generic PLA";"MyKlipper 0.4 nozzle"
; initial_layer_acceleration = 5000
; initial_layer_infill_speed = 75
; initial_layer_jerk = 2
; initial_layer_line_width = 0.56
; initial_layer_print_height = 0.36
; initial_layer_speed = 50
; initial_layer_travel_speed = 50%
; inner_wall_acceleration = 7500
; inner_wall_jerk = 2
; inner_wall_line_width = 0.42
; inner_wall_speed = 250
; interface_shells = 0
; internal_bridge_speed = 150%
; internal_bridge_support_thickness = 0
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.44
; internal_solid_infill_pattern = zig-zag
; internal_solid_infill_speed = 200
; ironing_flow = 10%
; ironing_pattern = zig-zag
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nAFTER_LAYER_CHANGE
; layer_height = 0.2
; line_width = 0.42
; machine_end_gcode = PRINT_END
; machine_load_filament_time = 0
; machine_max_acceleration_e = 3000,5000
; machine_max_acceleration_extruding = 3000,20000
; machine_max_acceleration_retracting = 3000,5000
; machine_max_acceleration_travel = 9000,9000
; machine_max_acceleration_x = 2500,20000
; machine_max_acceleration_y = 2500,20000
; machine_max_acceleration_z = 100,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 4,9
; machine_max_jerk_y = 4,9
; machine_max_jerk_z = 0.5,0.4
; machine_max_speed_e = 25,25
; machine_max_speed_x = 150,200
; machine_max_speed_y = 150,200
; machine_max_speed_z = 12,12
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_start_gcode = M190 S0 ; Remove this if autoemit_temperature_commands is off in Prusa Slicer 2.6 and later\nM109 S0 ; Remove this if autoemit_temperature_commands is off in Prusa Slicer 2.6 and later\n_PRINT_START_PHASE_INIT EXTRUDER={first_layer_temperature[initial_tool]} BED=[first_layer_bed_temperature] MESH_MIN={first_layer_print_min[0]},{first_layer_print_min[1]} MESH_MAX={first_layer_print_max[0]},{first_layer_print_max[1]} LAYERS={total_layer_count} NOZZLE_SIZE={nozzle_diameter[0]}\n; Insert custom gcode here.\n_PRINT_START_PHASE_PREHEAT\n; Insert custom gcode here.\n_PRINT_START_PHASE_PROBING\n; Insert custom gcode here.\n_PRINT_START_PHASE_EXTRUDER\n; Insert custom gcode here.\n_PRINT_START_PHASE_PURGE\n\n; This is the place to put slicer purge lines if you haven't set a non-zero\n; variable_start_purge_length to have START_PRINT automatically calculate and \n; perform the purge (e.g. if using a Mosaic Palette, which requires the slicer\n; to generate the purge).
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_travel_detour_distance = 25%
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 5
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 230
; nozzle_temperature_initial_layer = 230
; nozzle_temperature_range_high = 250
; nozzle_temperature_range_low = 190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; outer_wall_acceleration = 7500
; outer_wall_jerk = 2
; outer_wall_line_width = 0.44
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 25%
; overhang_speed_classic = 1
; post_process = 
; precise_outer_wall = 0
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "MyKlipper 0.4 nozzle"
; print_flow_ratio = 1
; print_host = 10.10.1.125
; print_host_webui = 
; print_sequence = by layer
; print_settings_id = 0.20mm Mercury1
; printable_area = 0x0,220x0,220x220,0x220
; printable_height = 250
; printer_model = Generic Klipper Printer
; printer_settings_id = Mercury1
; printer_technology = FFF
; printer_variant = 0.4
; printhost_apikey = 
; printhost_authorization_type = key
; printhost_cafile = 
; printhost_password = 
; printhost_port = 
; printhost_ssl_ignore_revoke = 0
; printhost_user = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 1
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_length = 0.4
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; seam_gap = 10%
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 1
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 20
; slow_down_layers = 1
; slow_down_min_speed = 50
; small_perimeter_speed = 50%
; small_perimeter_threshold = 10
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 20%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.5
; sparse_infill_pattern = adaptivecubic
; sparse_infill_speed = 250
; spiral_mode = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_pattern = rectilinear
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.4
; support_material_interface_fan_speed = -1
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thumbnails = 250x250
; timelapse_type = 0
; top_shell_layers = 5
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 7500
; top_surface_jerk = 2
; top_surface_line_width = 0.42
; top_surface_pattern = monotonic
; top_surface_speed = 200
; travel_acceleration = 7500
; travel_jerk = 2
; travel_speed = 300
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_diameter = 5
; tree_support_branch_distance = 5
; tree_support_brim_width = 3
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_infill_order = inner wall/outer wall/infill
; wall_loops = 3
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 155.000
; wipe_tower_y = 220.000
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; first_layer_bed_temperature = 60
; bed_shape = 0x0,220x0,220x220,0x220
; first_layer_temperature = 230
; first_layer_height = 0.360
; CONFIG_BLOCK_END


