; HEADER_BLOCK_START
; generated by OrcaSlicer 1.6.4-beta3 on 2023-08-17 at 19:23:29
; total layer number: 1
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START
; thumbnail begin 250x250 2124
; iVBORw0KGgoAAAANSUhEUgAAAPoAAAD6CAYAAACI7Fo9AAAF/0lEQVR4Ae3dy4pcVRgF4DNwoMYbKH
; S80ISQdDSCSDAYk4gFiuOMHah4QQcSMnTW4MSJEkEREUXfwEfoR/ARfAQfoe2d0LFTVFfVue/97++D
; NUtISKc4xdqLfZoGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAyMxne380X7920Dz+yDMNEMzumdeb767+0/z59uG9/PzWv82VZ281QBC3dvcffMCX88H5u57u
; ULL0FP/myt+nfsiPk35N+rVAYd5/8c7GD/jJpK/y6fcABUhfw29f/qvVh/xkUlH33KPnGiBTLz+9uP
; dk7vohV9RB5lKp1vcDrqiDTG1buHWNog5m1rZw6/NVPv1Znu4wofSBS6XZFB9yRR3M4ObOx5N/wJef
; 7unvAIwk7dTn/JCfTPq7+CoPA1reqeeSVNQ5hoMBrNup5xBFHfQw9rHZ0ElFnWM4aGGqY7Oxnu7AGu
; nrb06FW5+nu2M4WCHXwq3P011RByeMsVPPJfbyVK+0wq1r7OWpVqmFW9c4hqMqfS+GKD2KOsIb6mKI
; CE93e3lCily4dY29PGFEOzYbOvbyFK+2wq1rFHUUaa6LIUqPoo5izH0xROmxlyd7EXbqucSLIMmOwm
; 2c2MuTjdwvhogQe3lmU8tOPZfYyzM5x2bzRFHHJGrfqecSx3CMxk49r9jLMzg79XxjL09vjs3KSCrq
; 0jcuaE3hVlbs5WnFTr3sKOrYyE49RhzDcSo79Xixl+cBhVvspJ+tvXzl7NTrSPoqby9fITv1OuNFkB
; VxbFZ3FHXBRXmBoQwTx3ABKdxkVVxsEYidumyKoq5gCjdpExdbFEjhJl1iL18IF0PIEFHUZczFEDJk
; XGyRIYWbjBUXW2TAsZlMES+CnJGdukwZRd3EUkni2EzmiqJuAi6GkBxiLz8iO3XJLS62GJDCTXKOvf
; wAHJtJKbGX78BOXUqMvXwLdupSchzDbWCnLpHiGG4FO3WJGHv5ExRuEj1V7+Udm0lNqXIvr3CTGlNN
; UecFhiLBizo7dZH/E3Ivb6cusjoh9vIKN5HNKX4vv3tm0dy+fFDUP7rI1Lnz6kGz89iiKd6HFw6a32
; +W9Y8vMkU+OvpshHL+yUXzw5tl/RBExspP1w6bc08smpBS6fDlJU93qTtfXAr2FD/N4uz+UQFR1g9H
; pG/SU/zGzn5TFUWd1JSvXglSuHWVirpfr5f1QxPZNr/dCFi4dZWe7oo6iZbQhVsfijqJkk/3PMXXuv
; jUQlEnxSY9xS8c/R9mC8dFnae7lJTqC7eu3n1+X1En2ScVbu+9UNmx2dDS0/37q2X94KWe3D0qkV86
; +j/KQD7f81Ve8orCbSSpqHMMJ3PHsdkE7t//7uku86SanXouFHUyZX65XuFOPRf28jJFwlwMUToXW8
; hYsVPPjL28DBmFW+bs5aVvHJsVwl5eusROvUD28tImduqFcwwn62KnHoi9vKyKnXpQ9vJyHIVbcPby
; dcexWUUUdXVG4VYpRV0dSYXbO2cVblWzl48dO3UeYi8fL3bqrGQvHyMKN7ZiL19uXAxBK14EWVaqfI
; Ehw1DUlRHHZgzCMVyesVNncIq6vJK+qtupMxpF3fyxU2cSLraYJy6GYHL28tNG4casFHXjxk6dbLjY
; Ypx8+8ahpzj5cbHFcLFTJ2sutugXO3WK4UWQ3WKnTpFSUecYbnPs1Cmevfz6ODYjFBdbPJx0bKZwIy
; R7+ftRuFGFmvfydupUpba9vJ061aplL69wgybuXt7FELAk2l7eCwxhjQh7eYUbbKHUvbxjM2iptL18
; KtyAjnIv6lwMAQPJdS/vBYYwgpz28nbqMKK59/IKN5jQHHt5F0PADKZ6EaSLIWBmYxd1duqQkaGP4e
; zUIVND7eXt1KEAffbydupQkLSX//Fau8LNsRkUaNuLLRRuEMBpRZ2dOgSzfAxnpw6BfXLxwE4dAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMvQfw7Rxj6ZslI
; 4AAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.44mm
; perimeters extrusion width = 0.42mm
; infill extrusion width = 0.50mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.56mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=110,110 POLYGON=[[53.75,53.75],[166.25,53.75],[166.25,166.25],[53.75,166.25],[53.75,53.75]]
M73 P0 R8
;TYPE:Custom
M190 S0 ; Remove this if autoemit_temperature_commands is off in Prusa Slicer 2.6 and later
M109 S0 ; Remove this if autoemit_temperature_commands is off in Prusa Slicer 2.6 and later
_PRINT_START_PHASE_INIT EXTRUDER=230 BED=60 MESH_MIN=53.75,53.75 MESH_MAX=166.25,166.25 LAYERS=1 NOZZLE_SIZE=0.4
; Insert custom gcode here.
_PRINT_START_PHASE_PREHEAT
; Insert custom gcode here.
_PRINT_START_PHASE_PROBING
; Insert custom gcode here.
_PRINT_START_PHASE_EXTRUDER
; Insert custom gcode here.
_PRINT_START_PHASE_PURGE

; This is the place to put slicer purge lines if you haven't set a non-zero
; variable_start_purge_length to have START_PRINT automatically calculate and 
; perform the purge (e.g. if using a Mosaic Palette, which requires the slicer
; to generate the purge).
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
;LAYER_CHANGE
;Z:0.36
;HEIGHT:0.36
;BEFORE_LAYER_CHANGE
;0.36
BEFORE_LAYER_CHANGE HEIGHT=0.36 LAYER=0
G1 E-.4 F1800
;AFTER_LAYER_CHANGE
;0.36
AFTER_LAYER_CHANGE
SET_VELOCITY_LIMIT ACCEL=3000 ACCEL_TO_DECEL=1500
; printing object Cube id:0 copy 0
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 Z.4 F9000
G1 X54.995 Y54.995
G1 Z.4
G1 Z.36
G1 E.4 F1200
;TYPE:Inner wall
;WIDTH:0.56
G1 F3000
G1 X165.005 Y54.995 E8.17893
G1 X165.005 Y165.005 E8.17893
G1 X54.995 Y165.005 E8.17893
M73 P1 R8
G1 X54.995 Y55.035 E8.17596
G1 X54.513 Y54.513 F9000
G1 F3000
G1 X165.487 Y54.513 E8.25071
M73 P2 R8
G1 X165.487 Y165.487 E8.25071
G1 X54.513 Y165.487 E8.25071
M73 P3 R8
G1 X54.513 Y54.553 E8.24774
G1 X54.03 Y54.03 F9000
;TYPE:Outer wall
G1 F3000
G1 X165.97 Y54.03 E8.32249
G1 X165.97 Y165.97 E8.32249
M73 P4 R8
G1 X54.03 Y165.97 E8.32249
G1 X54.03 Y54.07 E8.31952
M73 P5 R8
G1 E-.4 F1800
G1 Z.76 F9000
G1 X163.882 Y55.14 Z.76
G1 Z.36
G1 E.4 F1200
;TYPE:Internal solid infill
;WIDTH:0.560854
G1 F3000
G1 X164.642 Y55.901 E.0801
G1 X164.642 Y56.585 E.05094
G1 X163.415 Y55.358 E.12925
G1 X162.731 Y55.358 E.05094
G1 X164.642 Y57.269 E.20129
G1 X164.642 Y57.952 E.05094
G1 X162.048 Y55.358 E.27332
G1 X161.364 Y55.358 E.05094
G1 X164.642 Y58.636 E.34536
G1 X164.642 Y59.32 E.05094
G1 X160.68 Y55.358 E.41739
G1 X159.996 Y55.358 E.05094
G1 X164.642 Y60.004 E.48943
G1 X164.642 Y60.688 E.05094
G1 X159.312 Y55.358 E.56147
G1 X158.628 Y55.358 E.05094
G1 X164.642 Y61.372 E.6335
G1 X164.642 Y62.056 E.05094
G1 X157.944 Y55.358 E.70554
G1 X157.26 Y55.358 E.05094
G1 X164.642 Y62.74 E.77757
G1 X164.642 Y63.424 E.05094
G1 X156.576 Y55.358 E.84961
G1 X155.892 Y55.358 E.05094
G1 X164.642 Y64.108 E.92165
G1 X164.642 Y64.792 E.05094
G1 X155.208 Y55.358 E.99368
G1 X154.525 Y55.358 E.05094
G1 X164.642 Y65.475 E1.06572
G1 X164.642 Y66.159 E.05094
G1 X153.841 Y55.358 E1.13775
G1 X153.157 Y55.358 E.05094
G1 X164.642 Y66.843 E1.20979
M73 P6 R8
G1 X164.642 Y67.527 E.05094
G1 X152.473 Y55.358 E1.28183
G1 X151.789 Y55.358 E.05094
G1 X164.642 Y68.211 E1.35386
G1 X164.642 Y68.895 E.05094
G1 X151.105 Y55.358 E1.4259
G1 X150.421 Y55.358 E.05094
G1 X164.642 Y69.579 E1.49793
G1 X164.642 Y70.263 E.05094
G1 X149.737 Y55.358 E1.56997
G1 X149.053 Y55.358 E.05094
G1 X164.642 Y70.947 E1.642
G1 X164.642 Y71.631 E.05094
G1 X148.369 Y55.358 E1.71404
G1 X147.685 Y55.358 E.05094
G1 X164.642 Y72.315 E1.78608
G1 X164.642 Y72.998 E.05094
G1 X147.002 Y55.358 E1.85811
G1 X146.318 Y55.358 E.05094
G1 X164.642 Y73.682 E1.93015
G1 X164.642 Y74.366 E.05094
G1 X145.634 Y55.358 E2.00218
M73 P7 R8
G1 X144.95 Y55.358 E.05094
G1 X164.642 Y75.05 E2.07422
G1 X164.642 Y75.734 E.05094
G1 X144.266 Y55.358 E2.14626
G1 X143.582 Y55.358 E.05094
G1 X164.642 Y76.418 E2.21829
G1 X164.642 Y77.102 E.05094
G1 X142.898 Y55.358 E2.29033
G1 X142.214 Y55.358 E.05094
G1 X164.642 Y77.786 E2.36236
G1 X164.642 Y78.47 E.05094
G1 X141.53 Y55.358 E2.4344
G1 X140.846 Y55.358 E.05094
G1 X164.642 Y79.154 E2.50644
G1 X164.642 Y79.838 E.05094
G1 X140.162 Y55.358 E2.57847
M73 P8 R8
G1 X139.479 Y55.358 E.05094
G1 X164.642 Y80.521 E2.65051
G1 X164.642 Y81.205 E.05094
G1 X138.795 Y55.358 E2.72254
G1 X138.111 Y55.358 E.05094
G1 X164.642 Y81.889 E2.79458
G1 X164.642 Y82.573 E.05094
G1 X137.427 Y55.358 E2.86662
G1 X136.743 Y55.358 E.05094
G1 X164.642 Y83.257 E2.93865
G1 X164.642 Y83.941 E.05094
G1 X136.059 Y55.358 E3.01069
G1 X135.375 Y55.358 E.05094
G1 X164.642 Y84.625 E3.08272
M73 P9 R8
G1 X164.642 Y85.309 E.05094
G1 X134.691 Y55.358 E3.15476
G1 X134.007 Y55.358 E.05094
G1 X164.642 Y85.993 E3.2268
G1 X164.642 Y86.677 E.05094
G1 X133.323 Y55.358 E3.29883
G1 X132.639 Y55.358 E.05094
G1 X164.642 Y87.361 E3.37087
G1 X164.642 Y88.044 E.05094
G1 X131.956 Y55.358 E3.4429
G1 X131.272 Y55.358 E.05094
G1 X164.642 Y88.728 E3.51494
M73 P10 R8
G1 X164.642 Y89.412 E.05094
G1 X130.588 Y55.358 E3.58697
G1 X129.904 Y55.358 E.05094
G1 X164.642 Y90.096 E3.65901
G1 X164.642 Y90.78 E.05094
G1 X129.22 Y55.358 E3.73105
M73 P10 R7
G1 X128.536 Y55.358 E.05094
G1 X164.642 Y91.464 E3.80308
G1 X164.642 Y92.148 E.05094
G1 X127.852 Y55.358 E3.87512
M73 P11 R7
G1 X127.168 Y55.358 E.05094
G1 X164.642 Y92.832 E3.94715
G1 X164.642 Y93.516 E.05094
G1 X126.484 Y55.358 E4.01919
G1 X125.8 Y55.358 E.05094
G1 X164.642 Y94.2 E4.09123
G1 X164.642 Y94.884 E.05094
G1 X125.116 Y55.358 E4.16326
G1 X124.433 Y55.358 E.05094
G1 X164.642 Y95.567 E4.2353
M73 P12 R7
G1 X164.642 Y96.251 E.05094
G1 X123.749 Y55.358 E4.30733
G1 X123.065 Y55.358 E.05094
G1 X164.642 Y96.935 E4.37937
G1 X164.642 Y97.619 E.05094
G1 X122.381 Y55.358 E4.45141
G1 X121.697 Y55.358 E.05094
G1 X164.642 Y98.303 E4.52344
M73 P13 R7
G1 X164.642 Y98.987 E.05094
G1 X121.013 Y55.358 E4.59548
G1 X120.329 Y55.358 E.05094
G1 X164.642 Y99.671 E4.66751
G1 X164.642 Y100.355 E.05094
G1 X119.645 Y55.358 E4.73955
G1 X118.961 Y55.358 E.05094
G1 X164.642 Y101.039 E4.81159
M73 P14 R7
G1 X164.642 Y101.723 E.05094
G1 X118.277 Y55.358 E4.88362
G1 X117.593 Y55.358 E.05094
G1 X164.642 Y102.407 E4.95566
G1 X164.642 Y103.09 E.05094
G1 X116.91 Y55.358 E5.02769
G1 X116.226 Y55.358 E.05094
G1 X164.642 Y103.774 E5.09973
M73 P15 R7
G1 X164.642 Y104.458 E.05094
G1 X115.542 Y55.358 E5.17177
G1 X114.858 Y55.358 E.05094
G1 X164.642 Y105.142 E5.2438
G1 X164.642 Y105.826 E.05094
G1 X114.174 Y55.358 E5.31584
G1 X113.49 Y55.358 E.05094
G1 X164.642 Y106.51 E5.38787
M73 P16 R7
G1 X164.642 Y107.194 E.05094
G1 X112.806 Y55.358 E5.45991
G1 X112.122 Y55.358 E.05094
G1 X164.642 Y107.878 E5.53194
G1 X164.642 Y108.562 E.05094
G1 X111.438 Y55.358 E5.60398
M73 P17 R7
G1 X110.754 Y55.358 E.05094
G1 X164.642 Y109.246 E5.67602
G1 X164.642 Y109.93 E.05094
G1 X110.07 Y55.358 E5.74805
G1 X109.387 Y55.358 E.05094
G1 X164.642 Y110.613 E5.82009
G1 X164.642 Y111.297 E.05094
G1 X108.703 Y55.358 E5.89212
M73 P18 R7
G1 X108.019 Y55.358 E.05094
G1 X164.642 Y111.981 E5.96416
G1 X164.642 Y112.665 E.05094
G1 X107.335 Y55.358 E6.0362
G1 X106.651 Y55.358 E.05094
G1 X164.642 Y113.349 E6.10823
M73 P19 R7
G1 X164.642 Y114.033 E.05094
G1 X105.967 Y55.358 E6.18027
G1 X105.283 Y55.358 E.05094
G1 X164.642 Y114.717 E6.2523
G1 X164.642 Y115.401 E.05094
G1 X104.599 Y55.358 E6.32434
M73 P20 R7
G1 X103.915 Y55.358 E.05094
G1 X164.642 Y116.085 E6.39638
G1 X164.642 Y116.769 E.05094
G1 X103.231 Y55.358 E6.46841
G1 X102.547 Y55.358 E.05094
G1 X164.642 Y117.453 E6.54045
M73 P21 R7
G1 X164.642 Y118.136 E.05094
G1 X101.864 Y55.358 E6.61248
G1 X101.18 Y55.358 E.05094
G1 X164.642 Y118.82 E6.68452
G1 X164.642 Y119.504 E.05094
G1 X100.496 Y55.358 E6.75656
M73 P22 R6
G1 X99.812 Y55.358 E.05094
G1 X164.642 Y120.188 E6.82859
G1 X164.642 Y120.872 E.05094
G1 X99.128 Y55.358 E6.90063
G1 X98.444 Y55.358 E.05094
G1 X164.642 Y121.556 E6.97266
M73 P23 R6
G1 X164.642 Y122.24 E.05094
G1 X97.76 Y55.358 E7.0447
G1 X97.076 Y55.358 E.05094
G1 X164.642 Y122.924 E7.11674
G1 X164.642 Y123.608 E.05094
G1 X96.392 Y55.358 E7.18877
M73 P24 R6
G1 X95.708 Y55.358 E.05094
G1 X164.642 Y124.292 E7.26081
G1 X164.642 Y124.976 E.05094
G1 X95.024 Y55.358 E7.33284
M73 P25 R6
G1 X94.341 Y55.358 E.05094
G1 X164.642 Y125.659 E7.40488
G1 X164.642 Y126.343 E.05094
G1 X93.657 Y55.358 E7.47691
G1 X92.973 Y55.358 E.05094
G1 X164.642 Y127.027 E7.54895
M73 P26 R6
G1 X164.642 Y127.711 E.05094
G1 X92.289 Y55.358 E7.62099
G1 X91.605 Y55.358 E.05094
G1 X164.642 Y128.395 E7.69302
G1 X164.642 Y129.079 E.05094
G1 X90.921 Y55.358 E7.76506
M73 P27 R6
G1 X90.237 Y55.358 E.05094
G1 X164.642 Y129.763 E7.83709
G1 X164.642 Y130.447 E.05094
G1 X89.553 Y55.358 E7.90913
M73 P28 R6
G1 X88.869 Y55.358 E.05094
G1 X164.642 Y131.131 E7.98117
G1 X164.642 Y131.815 E.05094
G1 X88.185 Y55.358 E8.0532
G1 X87.501 Y55.358 E.05094
G1 X164.642 Y132.499 E8.12524
M73 P29 R6
G1 X164.642 Y133.182 E.05094
G1 X86.818 Y55.358 E8.19727
G1 X86.134 Y55.358 E.05094
G1 X164.642 Y133.866 E8.26931
M73 P30 R6
G1 X164.642 Y134.55 E.05094
G1 X85.45 Y55.358 E8.34135
G1 X84.766 Y55.358 E.05094
G1 X164.642 Y135.234 E8.41338
M73 P31 R6
G1 X164.642 Y135.918 E.05094
G1 X84.082 Y55.358 E8.48542
G1 X83.398 Y55.358 E.05094
G1 X164.642 Y136.602 E8.55745
G1 X164.642 Y137.286 E.05094
G1 X82.714 Y55.358 E8.62949
M73 P32 R6
G1 X82.03 Y55.358 E.05094
G1 X164.642 Y137.97 E8.70153
G1 X164.642 Y138.654 E.05094
G1 X81.346 Y55.358 E8.77356
M73 P33 R5
G1 X80.662 Y55.358 E.05094
G1 X164.642 Y139.338 E8.8456
G1 X164.642 Y140.022 E.05094
G1 X79.978 Y55.358 E8.91763
M73 P34 R5
G1 X79.295 Y55.358 E.05094
G1 X164.642 Y140.705 E8.98967
G1 X164.642 Y141.389 E.05094
G1 X78.611 Y55.358 E9.06171
M73 P35 R5
G1 X77.927 Y55.358 E.05094
G1 X164.642 Y142.073 E9.13374
G1 X164.642 Y142.757 E.05094
G1 X77.243 Y55.358 E9.20578
M73 P36 R5
G1 X76.559 Y55.358 E.05094
G1 X164.642 Y143.441 E9.27781
G1 X164.642 Y144.125 E.05094
G1 X75.875 Y55.358 E9.34985
G1 X75.191 Y55.358 E.05094
M73 P37 R5
G1 X164.642 Y144.809 E9.42188
G1 X164.642 Y145.493 E.05094
G1 X74.507 Y55.358 E9.49392
G1 X73.823 Y55.358 E.05094
G1 X164.642 Y146.177 E9.56596
M73 P38 R5
G1 X164.642 Y146.861 E.05094
G1 X73.139 Y55.358 E9.63799
G1 X72.455 Y55.358 E.05094
G1 X164.642 Y147.545 E9.71003
M73 P39 R5
G1 X164.642 Y148.228 E.05094
G1 X71.772 Y55.358 E9.78206
G1 X71.088 Y55.358 E.05094
G1 X164.642 Y148.912 E9.8541
M73 P40 R5
G1 X164.642 Y149.596 E.05094
G1 X70.404 Y55.358 E9.92614
G1 X69.72 Y55.358 E.05094
G1 X164.642 Y150.28 E9.99817
M73 P41 R5
G1 X164.642 Y150.964 E.05094
G1 X69.036 Y55.358 E10.07021
G1 X68.352 Y55.358 E.05094
G1 X164.642 Y151.648 E10.14224
M73 P42 R5
G1 X164.642 Y152.332 E.05094
G1 X67.668 Y55.358 E10.21428
G1 X66.984 Y55.358 E.05094
G1 X164.642 Y153.016 E10.28632
M73 P43 R5
G1 X164.642 Y153.7 E.05094
G1 X66.3 Y55.358 E10.35835
M73 P44 R5
G1 X65.616 Y55.358 E.05094
G1 X164.642 Y154.384 E10.43039
M73 P44 R4
G1 X164.642 Y155.068 E.05094
G1 X64.932 Y55.358 E10.50242
M73 P45 R4
G1 X64.249 Y55.358 E.05094
G1 X164.642 Y155.752 E10.57446
G1 X164.642 Y156.435 E.05094
G1 X63.565 Y55.358 E10.6465
M73 P46 R4
G1 X62.881 Y55.358 E.05094
G1 X164.642 Y157.119 E10.71853
G1 X164.642 Y157.803 E.05094
G1 X62.197 Y55.358 E10.79057
M73 P47 R4
G1 X61.513 Y55.358 E.05094
G1 X164.642 Y158.487 E10.8626
G1 X164.642 Y159.171 E.05094
G1 X60.829 Y55.358 E10.93464
M73 P48 R4
G1 X60.145 Y55.358 E.05094
G1 X164.642 Y159.855 E11.00668
G1 X164.642 Y160.539 E.05094
G1 X59.461 Y55.358 E11.07871
M73 P49 R4
G1 X58.777 Y55.358 E.05094
G1 X164.642 Y161.223 E11.15075
M73 P50 R4
G1 X164.642 Y161.907 E.05094
G1 X58.093 Y55.358 E11.22278
G1 X57.409 Y55.358 E.05094
G1 X164.642 Y162.591 E11.29482
M73 P51 R4
G1 X164.642 Y163.275 E.05094
G1 X56.725 Y55.358 E11.36685
G1 X56.042 Y55.358 E.05094
G1 X164.642 Y163.958 E11.43889
M73 P52 R4
G1 X164.642 Y164.642 E.05094
G1 X55.358 Y55.358 E11.51093
G1 X55.358 Y56.041 E.05093
G1 X163.959 Y164.642 E11.43892
M73 P53 R4
G1 X163.275 Y164.642 E.05094
G1 X55.358 Y56.725 E11.36689
M73 P54 R4
G1 X55.358 Y57.409 E.05094
G1 X162.591 Y164.642 E11.29485
G1 X161.907 Y164.642 E.05094
G1 X55.358 Y58.093 E11.22281
M73 P55 R4
G1 X55.358 Y58.777 E.05094
G1 X161.223 Y164.642 E11.15078
M73 P55 R3
G1 X160.539 Y164.642 E.05094
G1 X55.358 Y59.461 E11.07874
M73 P56 R3
G1 X55.358 Y60.145 E.05094
G1 X159.855 Y164.642 E11.00671
G1 X159.171 Y164.642 E.05094
G1 X55.358 Y60.829 E10.93467
M73 P57 R3
G1 X55.358 Y61.513 E.05094
G1 X158.487 Y164.642 E10.86263
M73 P58 R3
G1 X157.804 Y164.642 E.05094
G1 X55.358 Y62.196 E10.7906
G1 X55.358 Y62.88 E.05094
G1 X157.12 Y164.642 E10.71856
M73 P59 R3
G1 X156.436 Y164.642 E.05094
G1 X55.358 Y63.564 E10.64653
G1 X55.358 Y64.248 E.05094
G1 X155.752 Y164.642 E10.57449
M73 P60 R3
G1 X155.068 Y164.642 E.05094
G1 X55.358 Y64.932 E10.50245
G1 X55.358 Y65.616 E.05094
G1 X154.384 Y164.642 E10.43042
M73 P61 R3
G1 X153.7 Y164.642 E.05094
G1 X55.358 Y66.3 E10.35838
G1 X55.358 Y66.984 E.05094
G1 X153.016 Y164.642 E10.28635
M73 P62 R3
G1 X152.332 Y164.642 E.05094
G1 X55.358 Y67.668 E10.21431
G1 X55.358 Y68.352 E.05094
G1 X151.648 Y164.642 E10.14228
M73 P63 R3
G1 X150.964 Y164.642 E.05094
G1 X55.358 Y69.036 E10.07024
G1 X55.358 Y69.719 E.05094
G1 X150.281 Y164.642 E9.9982
M73 P64 R3
G1 X149.597 Y164.642 E.05094
G1 X55.358 Y70.403 E9.92617
G1 X55.358 Y71.087 E.05094
G1 X148.913 Y164.642 E9.85413
M73 P65 R3
G1 X148.229 Y164.642 E.05094
G1 X55.358 Y71.771 E9.7821
G1 X55.358 Y72.455 E.05094
G1 X147.545 Y164.642 E9.71006
M73 P66 R3
G1 X146.861 Y164.642 E.05094
G1 X55.358 Y73.139 E9.63802
M73 P66 R2
G1 X55.358 Y73.823 E.05094
G1 X146.177 Y164.642 E9.56599
M73 P67 R2
G1 X145.493 Y164.642 E.05094
G1 X55.358 Y74.507 E9.49395
G1 X55.358 Y75.191 E.05094
G1 X144.809 Y164.642 E9.42192
M73 P68 R2
G1 X144.125 Y164.642 E.05094
G1 X55.358 Y75.875 E9.34988
G1 X55.358 Y76.559 E.05094
G1 X143.441 Y164.642 E9.27784
M73 P69 R2
G1 X142.758 Y164.642 E.05094
G1 X55.358 Y77.242 E9.20581
G1 X55.358 Y77.926 E.05094
G1 X142.074 Y164.642 E9.13377
M73 P70 R2
G1 X141.39 Y164.642 E.05094
G1 X55.358 Y78.61 E9.06174
G1 X55.358 Y79.294 E.05094
G1 X140.706 Y164.642 E8.9897
M73 P71 R2
G1 X140.022 Y164.642 E.05094
G1 X55.358 Y79.978 E8.91766
G1 X55.358 Y80.662 E.05094
G1 X139.338 Y164.642 E8.84563
M73 P72 R2
G1 X138.654 Y164.642 E.05094
G1 X55.358 Y81.346 E8.77359
G1 X55.358 Y82.03 E.05094
G1 X137.97 Y164.642 E8.70156
G1 X137.286 Y164.642 E.05094
G1 X55.358 Y82.714 E8.62952
M73 P73 R2
G1 X55.358 Y83.398 E.05094
G1 X136.602 Y164.642 E8.55748
G1 X135.918 Y164.642 E.05094
G1 X55.358 Y84.082 E8.48545
M73 P74 R2
G1 X55.358 Y84.765 E.05094
G1 X135.235 Y164.642 E8.41341
G1 X134.551 Y164.642 E.05094
G1 X55.358 Y85.449 E8.34138
M73 P75 R2
G1 X55.358 Y86.133 E.05094
G1 X133.867 Y164.642 E8.26934
G1 X133.183 Y164.642 E.05094
G1 X55.358 Y86.817 E8.19731
G1 X55.358 Y87.501 E.05094
G1 X132.499 Y164.642 E8.12527
M73 P76 R2
G1 X131.815 Y164.642 E.05094
G1 X55.358 Y88.185 E8.05323
G1 X55.358 Y88.869 E.05094
G1 X131.131 Y164.642 E7.9812
M73 P77 R2
G1 X130.447 Y164.642 E.05094
G1 X55.358 Y89.553 E7.90916
G1 X55.358 Y90.237 E.05094
G1 X129.763 Y164.642 E7.83713
M73 P77 R1
G1 X129.079 Y164.642 E.05094
G1 X55.358 Y90.921 E7.76509
M73 P78 R1
G1 X55.358 Y91.605 E.05094
G1 X128.395 Y164.642 E7.69305
G1 X127.712 Y164.642 E.05094
G1 X55.358 Y92.288 E7.62102
M73 P79 R1
G1 X55.358 Y92.972 E.05094
G1 X127.028 Y164.642 E7.54898
G1 X126.344 Y164.642 E.05094
G1 X55.358 Y93.656 E7.47695
G1 X55.358 Y94.34 E.05094
G1 X125.66 Y164.642 E7.40491
M73 P80 R1
G1 X124.976 Y164.642 E.05094
G1 X55.358 Y95.024 E7.33287
G1 X55.358 Y95.708 E.05094
G1 X124.292 Y164.642 E7.26084
M73 P81 R1
G1 X123.608 Y164.642 E.05094
G1 X55.358 Y96.392 E7.1888
G1 X55.358 Y97.076 E.05094
G1 X122.924 Y164.642 E7.11677
G1 X122.24 Y164.642 E.05094
G1 X55.358 Y97.76 E7.04473
M73 P82 R1
G1 X55.358 Y98.444 E.05094
G1 X121.556 Y164.642 E6.97269
G1 X120.872 Y164.642 E.05094
G1 X55.358 Y99.128 E6.90066
G1 X55.358 Y99.811 E.05094
G1 X120.189 Y164.642 E6.82862
M73 P83 R1
G1 X119.505 Y164.642 E.05094
G1 X55.358 Y100.495 E6.75659
G1 X55.358 Y101.179 E.05094
G1 X118.821 Y164.642 E6.68455
G1 X118.137 Y164.642 E.05094
G1 X55.358 Y101.863 E6.61251
M73 P84 R1
G1 X55.358 Y102.547 E.05094
G1 X117.453 Y164.642 E6.54048
G1 X116.769 Y164.642 E.05094
G1 X55.358 Y103.231 E6.46844
G1 X55.358 Y103.915 E.05094
G1 X116.085 Y164.642 E6.39641
M73 P85 R1
G1 X115.401 Y164.642 E.05094
G1 X55.358 Y104.599 E6.32437
G1 X55.358 Y105.283 E.05094
G1 X114.717 Y164.642 E6.25233
G1 X114.033 Y164.642 E.05094
G1 X55.358 Y105.967 E6.1803
M73 P86 R1
G1 X55.358 Y106.651 E.05094
G1 X113.349 Y164.642 E6.10826
G1 X112.665 Y164.642 E.05094
G1 X55.358 Y107.335 E6.03623
G1 X55.358 Y108.018 E.05094
G1 X111.982 Y164.642 E5.96419
M73 P87 R1
G1 X111.298 Y164.642 E.05094
G1 X55.358 Y108.702 E5.89216
G1 X55.358 Y109.386 E.05094
G1 X110.614 Y164.642 E5.82012
G1 X109.93 Y164.642 E.05094
G1 X55.358 Y110.07 E5.74808
M73 P88 R1
G1 X55.358 Y110.754 E.05094
G1 X109.246 Y164.642 E5.67605
G1 X108.562 Y164.642 E.05094
G1 X55.358 Y111.438 E5.60401
G1 X55.358 Y112.122 E.05094
G1 X107.878 Y164.642 E5.53198
G1 X107.194 Y164.642 E.05094
G1 X55.358 Y112.806 E5.45994
M73 P89 R0
G1 X55.358 Y113.49 E.05094
G1 X106.51 Y164.642 E5.3879
G1 X105.826 Y164.642 E.05094
G1 X55.358 Y114.174 E5.31587
G1 X55.358 Y114.858 E.05094
G1 X105.142 Y164.642 E5.24383
G1 X104.459 Y164.642 E.05094
G1 X55.358 Y115.541 E5.1718
M73 P90 R0
G1 X55.358 Y116.225 E.05094
G1 X103.775 Y164.642 E5.09976
G1 X103.091 Y164.642 E.05094
G1 X55.358 Y116.909 E5.02772
G1 X55.358 Y117.593 E.05094
G1 X102.407 Y164.642 E4.95569
M73 P91 R0
G1 X101.723 Y164.642 E.05094
G1 X55.358 Y118.277 E4.88365
G1 X55.358 Y118.961 E.05094
G1 X101.039 Y164.642 E4.81162
G1 X100.355 Y164.642 E.05094
G1 X55.358 Y119.645 E4.73958
G1 X55.358 Y120.329 E.05094
G1 X99.671 Y164.642 E4.66754
M73 P92 R0
G1 X98.987 Y164.642 E.05094
G1 X55.358 Y121.013 E4.59551
G1 X55.358 Y121.697 E.05094
G1 X98.303 Y164.642 E4.52347
G1 X97.619 Y164.642 E.05094
G1 X55.358 Y122.381 E4.45144
G1 X55.358 Y123.064 E.05094
G1 X96.936 Y164.642 E4.3794
G1 X96.252 Y164.642 E.05094
G1 X55.358 Y123.748 E4.30736
M73 P93 R0
G1 X55.358 Y124.432 E.05094
G1 X95.568 Y164.642 E4.23533
G1 X94.884 Y164.642 E.05094
G1 X55.358 Y125.116 E4.16329
G1 X55.358 Y125.8 E.05094
G1 X94.2 Y164.642 E4.09126
G1 X93.516 Y164.642 E.05094
G1 X55.358 Y126.484 E4.01922
M73 P94 R0
G1 X55.358 Y127.168 E.05094
G1 X92.832 Y164.642 E3.94719
G1 X92.148 Y164.642 E.05094
G1 X55.358 Y127.852 E3.87515
G1 X55.358 Y128.536 E.05094
G1 X91.464 Y164.642 E3.80311
G1 X90.78 Y164.642 E.05094
G1 X55.358 Y129.22 E3.73108
G1 X55.358 Y129.904 E.05094
G1 X90.096 Y164.642 E3.65904
M73 P95 R0
G1 X89.413 Y164.642 E.05094
G1 X55.358 Y130.587 E3.58701
G1 X55.358 Y131.271 E.05094
G1 X88.729 Y164.642 E3.51497
G1 X88.045 Y164.642 E.05094
G1 X55.358 Y131.955 E3.44293
G1 X55.358 Y132.639 E.05094
G1 X87.361 Y164.642 E3.3709
G1 X86.677 Y164.642 E.05094
G1 X55.358 Y133.323 E3.29886
G1 X55.358 Y134.007 E.05094
G1 X85.993 Y164.642 E3.22683
M73 P96 R0
G1 X85.309 Y164.642 E.05094
G1 X55.358 Y134.691 E3.15479
G1 X55.358 Y135.375 E.05094
G1 X84.625 Y164.642 E3.08275
G1 X83.941 Y164.642 E.05094
G1 X55.358 Y136.059 E3.01072
G1 X55.358 Y136.743 E.05094
G1 X83.257 Y164.642 E2.93868
G1 X82.573 Y164.642 E.05094
G1 X55.358 Y137.427 E2.86665
G1 X55.358 Y138.11 E.05094
G1 X81.89 Y164.642 E2.79461
M73 P97 R0
G1 X81.206 Y164.642 E.05094
G1 X55.358 Y138.794 E2.72257
G1 X55.358 Y139.478 E.05094
G1 X80.522 Y164.642 E2.65054
G1 X79.838 Y164.642 E.05094
G1 X55.358 Y140.162 E2.5785
G1 X55.358 Y140.846 E.05094
G1 X79.154 Y164.642 E2.50647
G1 X78.47 Y164.642 E.05094
G1 X55.358 Y141.53 E2.43443
G1 X55.358 Y142.214 E.05094
G1 X77.786 Y164.642 E2.36239
G1 X77.102 Y164.642 E.05094
G1 X55.358 Y142.898 E2.29036
G1 X55.358 Y143.582 E.05094
G1 X76.418 Y164.642 E2.21832
M73 P98 R0
G1 X75.734 Y164.642 E.05094
G1 X55.358 Y144.266 E2.14629
G1 X55.358 Y144.95 E.05094
G1 X75.05 Y164.642 E2.07425
G1 X74.367 Y164.642 E.05094
G1 X55.358 Y145.633 E2.00222
G1 X55.358 Y146.317 E.05094
G1 X73.683 Y164.642 E1.93018
G1 X72.999 Y164.642 E.05094
G1 X55.358 Y147.001 E1.85814
G1 X55.358 Y147.685 E.05094
G1 X72.315 Y164.642 E1.78611
G1 X71.631 Y164.642 E.05094
G1 X55.358 Y148.369 E1.71407
G1 X55.358 Y149.053 E.05094
G1 X70.947 Y164.642 E1.64204
G1 X70.263 Y164.642 E.05094
G1 X55.358 Y149.737 E1.57
G1 X55.358 Y150.421 E.05094
M73 P99 R0
G1 X69.579 Y164.642 E1.49796
G1 X68.895 Y164.642 E.05094
G1 X55.358 Y151.105 E1.42593
G1 X55.358 Y151.789 E.05094
G1 X68.211 Y164.642 E1.35389
G1 X67.527 Y164.642 E.05094
G1 X55.358 Y152.473 E1.28186
G1 X55.358 Y153.156 E.05094
G1 X66.844 Y164.642 E1.20982
G1 X66.16 Y164.642 E.05094
G1 X55.358 Y153.84 E1.13778
G1 X55.358 Y154.524 E.05094
G1 X65.476 Y164.642 E1.06575
G1 X64.792 Y164.642 E.05094
G1 X55.358 Y155.208 E.99371
G1 X55.358 Y155.892 E.05094
G1 X64.108 Y164.642 E.92168
G1 X63.424 Y164.642 E.05094
G1 X55.358 Y156.576 E.84964
G1 X55.358 Y157.26 E.05094
G1 X62.74 Y164.642 E.7776
G1 X62.056 Y164.642 E.05094
G1 X55.358 Y157.944 E.70557
G1 X55.358 Y158.628 E.05094
G1 X61.372 Y164.642 E.63353
G1 X60.688 Y164.642 E.05094
G1 X55.358 Y159.312 E.5615
G1 X55.358 Y159.996 E.05094
G1 X60.004 Y164.642 E.48946
G1 X59.321 Y164.642 E.05094
G1 X55.358 Y160.679 E.41742
G1 X55.358 Y161.363 E.05094
G1 X58.637 Y164.642 E.34539
G1 X57.953 Y164.642 E.05094
G1 X55.358 Y162.047 E.27335
G1 X55.358 Y162.731 E.05094
G1 X57.269 Y164.642 E.20132
G1 X56.585 Y164.642 E.05094
G1 X55.358 Y163.415 E.12928
G1 X55.358 Y164.099 E.05094
G1 X56.118 Y164.86 E.08013
; stop printing object Cube id:0 copy 0
G1 E-.28 F1800
;WIPE_START
G1 F3000
G1 X55.411 Y164.153 E-.114
;WIPE_END
G1 E-.006 F1800
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
M106 S0
;TYPE:Custom
; filament end gcode 
PRINT_END
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 1954.24
; filament used [cm3] = 4.70
; filament used [g] = 5.83
; filament cost = 0.12; total filament used [g] = 5.83
; total filament cost = 0.12
; total layers count = 1
; estimated printing time (normal mode) = 8m 56s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; additional_cooling_fan_speed = 70
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_temperature_difference = 10
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nBEFORE_LAYER_CHANGE HEIGHT=[layer_z] LAYER=[layer_num]
; bottom_shell_layers = 4
; bottom_shell_thickness = 1
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 0
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; curr_bed_type = High Temp Plate
; default_acceleration = 10000
; default_filament_colour = ""
; default_filament_profile = "My Generic ABS"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @MyKlipper
; deretraction_speed = 20
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = bottom_shell_layers;bottom_shell_thickness;default_acceleration;filter_out_gap_fill;gap_infill_speed;infill_combination;infill_jerk;initial_layer_acceleration;initial_layer_infill_speed;initial_layer_jerk;initial_layer_line_width;initial_layer_print_height;initial_layer_travel_speed;inner_wall_acceleration;inner_wall_jerk;inner_wall_line_width;inner_wall_speed;internal_solid_infill_line_width;line_width;max_travel_detour_distance;minimum_sparse_infill_area;outer_wall_acceleration;outer_wall_jerk;outer_wall_line_width;outer_wall_speed;reduce_crossing_wall;seam_position;slow_down_layers;small_perimeter_threshold;sparse_infill_density;sparse_infill_line_width;sparse_infill_pattern;sparse_infill_speed;top_shell_layers;top_shell_thickness;top_surface_acceleration;top_surface_jerk;top_surface_line_width;top_surface_speed;travel_acceleration;travel_jerk;travel_speed;wall_generator;fan_cooling_layer_time;fan_min_speed;filament_flow_ratio;filament_max_volumetric_speed;nozzle_temperature;nozzle_temperature_initial_layer;nozzle_temperature_range_high;overhang_fan_threshold;slow_down_layer_time;slow_down_min_speed;before_layer_change_gcode;deretraction_speed;fan_kickstart;fan_speedup_time;layer_change_gcode;machine_max_acceleration_e;machine_max_acceleration_extruding;machine_max_acceleration_retracting;machine_max_acceleration_x;machine_max_acceleration_y;machine_max_acceleration_z;machine_max_jerk_x;machine_max_jerk_y;machine_max_jerk_z;machine_max_speed_x;machine_max_speed_y;machine_start_gcode;print_host;printable_area;retraction_length;thumbnails
; draft_shield = disabled
; elefant_foot_compensation = 0
; enable_arc_fitting = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = 1
; exclude_object = 1
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 60
; fan_kickstart = 2
; fan_max_speed = 100
; fan_min_speed = 40
; fan_speedup_overhangs = 1
; fan_speedup_time = 1
; filament_colour = #00AE42
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 1.029
; filament_ids = GFL99
; filament_is_support = 0
; filament_max_volumetric_speed = 18
; filament_minimal_purge_on_wipe_tower = 15
; filament_settings_id = "Mercury1 - PLA"
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_type = PLA
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 5
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; host_type = octoprint
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 1
; infill_direction = 45
; infill_jerk = 2
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @MyKlipper";"My Generic PLA";"MyKlipper 0.4 nozzle"
; initial_layer_acceleration = 5000
; initial_layer_infill_speed = 75
; initial_layer_jerk = 2
; initial_layer_line_width = 0.56
; initial_layer_print_height = 0.36
; initial_layer_speed = 50
; initial_layer_travel_speed = 50%
; inner_wall_acceleration = 7500
; inner_wall_jerk = 2
; inner_wall_line_width = 0.42
; inner_wall_speed = 250
; interface_shells = 0
; internal_bridge_speed = 150%
; internal_bridge_support_thickness = 0
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.44
; internal_solid_infill_pattern = zig-zag
; internal_solid_infill_speed = 200
; ironing_flow = 10%
; ironing_pattern = zig-zag
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nAFTER_LAYER_CHANGE
; layer_height = 0.2
; line_width = 0.42
; machine_end_gcode = PRINT_END
; machine_load_filament_time = 0
; machine_max_acceleration_e = 3000,5000
; machine_max_acceleration_extruding = 3000,20000
; machine_max_acceleration_retracting = 3000,5000
; machine_max_acceleration_travel = 9000,9000
; machine_max_acceleration_x = 2500,20000
; machine_max_acceleration_y = 2500,20000
; machine_max_acceleration_z = 100,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 4,9
; machine_max_jerk_y = 4,9
; machine_max_jerk_z = 0.5,0.4
; machine_max_speed_e = 25,25
; machine_max_speed_x = 150,200
; machine_max_speed_y = 150,200
; machine_max_speed_z = 12,12
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_start_gcode = M190 S0 ; Remove this if autoemit_temperature_commands is off in Prusa Slicer 2.6 and later\nM109 S0 ; Remove this if autoemit_temperature_commands is off in Prusa Slicer 2.6 and later\n_PRINT_START_PHASE_INIT EXTRUDER={first_layer_temperature[initial_tool]} BED=[first_layer_bed_temperature] MESH_MIN={first_layer_print_min[0]},{first_layer_print_min[1]} MESH_MAX={first_layer_print_max[0]},{first_layer_print_max[1]} LAYERS={total_layer_count} NOZZLE_SIZE={nozzle_diameter[0]}\n; Insert custom gcode here.\n_PRINT_START_PHASE_PREHEAT\n; Insert custom gcode here.\n_PRINT_START_PHASE_PROBING\n; Insert custom gcode here.\n_PRINT_START_PHASE_EXTRUDER\n; Insert custom gcode here.\n_PRINT_START_PHASE_PURGE\n\n; This is the place to put slicer purge lines if you haven't set a non-zero\n; variable_start_purge_length to have START_PRINT automatically calculate and \n; perform the purge (e.g. if using a Mosaic Palette, which requires the slicer\n; to generate the purge).
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_travel_detour_distance = 25%
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 5
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 230
; nozzle_temperature_initial_layer = 230
; nozzle_temperature_range_high = 250
; nozzle_temperature_range_low = 190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; outer_wall_acceleration = 7500
; outer_wall_jerk = 2
; outer_wall_line_width = 0.44
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 25%
; overhang_speed_classic = 1
; post_process = 
; precise_outer_wall = 0
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "MyKlipper 0.4 nozzle"
; print_flow_ratio = 1
; print_host = 10.10.1.125
; print_host_webui = 
; print_sequence = by layer
; print_settings_id = 0.20mm Mercury1
; printable_area = 0x0,220x0,220x220,0x220
; printable_height = 250
; printer_model = Generic Klipper Printer
; printer_settings_id = Mercury1
; printer_technology = FFF
; printer_variant = 0.4
; printhost_apikey = 
; printhost_authorization_type = key
; printhost_cafile = 
; printhost_password = 
; printhost_port = 
; printhost_ssl_ignore_revoke = 0
; printhost_user = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 1
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_length = 0.4
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; seam_gap = 10%
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 1
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 20
; slow_down_layers = 1
; slow_down_min_speed = 50
; small_perimeter_speed = 50%
; small_perimeter_threshold = 10
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 20%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.5
; sparse_infill_pattern = adaptivecubic
; sparse_infill_speed = 250
; spiral_mode = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_pattern = rectilinear
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.4
; support_material_interface_fan_speed = -1
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thumbnails = 250x250
; timelapse_type = 0
; top_shell_layers = 5
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 7500
; top_surface_jerk = 2
; top_surface_line_width = 0.42
; top_surface_pattern = monotonic
; top_surface_speed = 200
; travel_acceleration = 7500
; travel_jerk = 2
; travel_speed = 300
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_diameter = 5
; tree_support_branch_distance = 5
; tree_support_brim_width = 3
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_infill_order = inner wall/outer wall/infill
; wall_loops = 3
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 155.000
; wipe_tower_y = 220.000
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; first_layer_bed_temperature = 60
; bed_shape = 0x0,220x0,220x220,0x220
; first_layer_temperature = 230
; first_layer_height = 0.360
; CONFIG_BLOCK_END


